hostname: oz
ip: "192.168.33.12"

synced_folder:
  - host: "~/dev/gongzuo"
    guest: "/home/vagrant/dev/gongzuo"
    type: nfs

  - host: "~/hcl"
    guest: "/home/vagrant/hcl"
    type: nfs_guest

forward_port:
  - guest: 8080
  - host: 8080
