box: ubuntu/focal64
hostname: oz
public_network:
  ip: "192.168.1.201"
  bridge: "eno1"
private_network:
  ip: "192.168.33.10"

synced_folder:
  - host: "~/dev/gongzuo"
    guest: "/home/vagrant/dev/gongzuo"
    type: nfs

  - host: "~/hcl"
    guest: "/home/vagrant/hcl"
    type: nfs_guest

forward_port:
  - guest: 8080
  - host: 8080
