# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
if [[ -f /.dockerinit || -f /.dockerenv ]]
then
    ZSH_THEME="gozilla"
else
    if [[ $OSTYPE == darwin* ]]
    then
        # ZSH_THEME="cliff-mac"
        ZSH_THEME="robbyrussell"
    else
        prof_file=$(print /etc/*-release) 2>/dev/null
        if [[ -z $prof_file ]]
        then
            ZSH_THEME="cliff-linux"
        else
            if [[ $(cat `echo $prof_file`) =~ .*Ubuntu.* ]]
            then
                ZSH_THEME="cliff-ubuntu"
            elif [[ $(cat `echo $prof_file`) =~ .*Arch.* ]]
            then
                ZSH_THEME="cliff-arch"
            else
                ZSH_THEME="cliff-linux"
            fi
        fi
        unset prof_file
    fi
fi

if [[ -n $EMACS ]]
then
    ZSH_THEME="gozilla"
fi

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

if [[ -z $EMACS ]] && [[ -z $NVIM_LISTEN_ADDRESS ]]
then
    plugins=(vi-mode)
fi

source $ZSH/oh-my-zsh.sh

if [[ -f $HOME/.shrc ]]
then
    source $HOME/.shrc
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# item2 shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
