#!/usr/bin/env bash
ms=(0 1 3 4 5 7)
printf "\134e[_m\t"
for j in {30..37}
do
  printf "\e[%sm%s" "$j" "$j"
done
printf "\e[0m\t"

for j in {40..47}
do
  printf "\e[%sm%s" "$j" "$j"
done

printf "\e[0m\n"
for i in "${ms[@]}"
do
  printf "\134e[%s;_m\t" "$i"
  for j in {30..37}
  do
    printf "\e[%s;%sm%s" "$i" "$j" "$j"
  done
  printf "\e[0m\t"

  for j in {40..47}
  do
    printf "\e[%s;%sm%s" "$i" "$j" "$j"
  done
  printf "\e[0m\n"
done

printf "\134e[1;31;4;43mcliff xuan\t\t\e[1;31;4;43mcliff xuan"
printf "\e[0m\n"
