#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
get rid of dos format and utf-16
"""
import argparse
import sys


def argument_parser():
    parser = argparse.ArgumentParser(
        description='describe me')
    parser.add_argument(
        'filename', type=argparse.FileType('r'),
        help='name of the file to convert')
    return parser


def main(argv=None):
    args = argument_parser().parse_args(argv)
    txt = args.filename.read()
    try:
        txt = txt.decode('utf-16').encode('utf-8')
    except UnicodeDecodeError:
        sys.stderr.write('maybe not a dos format file?')
    else:
        txt = txt.replace('\r\n', '\n')
    print txt


if __name__ == '__main__':
    main()
