#!/bin/bash
#
# Simple creation of a single-app django project, as described in: https://zindilis.com/blog/2017/01/06/django-anatomy-for-single-app.html
#
# ./dj-init foo bar
#
# This will result is the following flat structure:
#
# .
# └── foo
#     ├── manage.py
#     ├── settings.py
#     ├── urls.py
#     ├── bar
#     │   ├── __init__.py
#     │   ├── admin.py
#     │   ├── apps.py
#     │   ├── migrations
#     │   │   └── __init__.py
#     │   ├── models.py
#     │   ├── tests.py
#     │   └── views.py
#     └── wsgi.py
# Note: this script assumes a GNU-compatible sed is installed.

[ -z "$1" ] && echo "must provide a project name" && exit 1 || prj="$1"
app=${2:-$prj}

echo project=$prj app=$app

django-admin startproject $prj
cd $prj
mv $prj/* .
rm __init__.py
rm -rf $prj
sed -i 's/'"${prj}"'\.settings/settings/g' manage.py wsgi.py
sed -i 's/'"${prj}"'\.urls/urls/g' settings.py
sed -i 's/'"${prj}"'\.wsgi\.application/wsgi.application/g' settings.py
sed -i 's/os.path.dirname(os.path.dirname(os.path.abspath(__file__)))/os.path.dirname(os.path.abspath(__file__))/g' settings.py
sed -i 's/'"${prj}"'\.wsgi\.application/wsgi.application/g' settings.py
./manage.py startapp ${app}
