#!/usr/bin/env bash
if ! hash sgpt 2>/dev/null; then
  echo "cannot find shell-gtp. run pip install shell-gtp"
  exit 1
fi

OPENAI_API_KEY="$(openaikey)"
if [ -z "$OPENAI_API_KEY" ]; then
  echo "OPENAI_API_KEY is not set."
  exit 1
fi

quoted_args=$(printf "%s " "$@")
echo "sgpt $quoted_args"
OPENAI_API_KEY="$OPENAI_API_KEY" sgpt "$quoted_args"
