#!/usr/bin/env bash

for file in /tmp/openai_api_key "$HOME"/.config/openai_api_key; do
  if [ -f "$file" ]; then
    cat "$file"
    exit 0
  fi
done

if [[ -n $OPENAI_API_KEY ]]; then
  echo "$OPENAI_API_KEY"
fi

exit 0
