#!/usr/bin/env bash
#
mk_cargo() {
  filename="$1"
  direcotry=$(dirname "$filename")
  bname=$(basename "$filename")
  cd "$direcotry" || exit 1
  cat <<EOF >Cargo.toml
[package]
name = "${bname%.*}"
version = "0.1.0"
edition = "2021"
EOF
}

setup() {
  dirname="$1"
  filename="$2"
  cargo_file="$3"
  cp "$filename" "$dirname/"
  if [ -z "$cargo_file" ]; then
    mk_cargo "$dirname/$(basename "$filename")"
  else
    cp "$cargo_file" "$dirname/Cargo.toml"
  fi
  bname=$(basename "$filename")
  cat <<EOF >> "$dirname/Cargo.toml"

[[bin]]
name = "${bname%.*}"
path = "$bname"
EOF
    echo "$dirname/Cargo.toml"
    cat "$dirname/Cargo.toml"
}

cargo_run() {
  curdir=$(dirname "$1")
  echo "$curdir"
  if [ -f "$curdir/Cargo.toml" ]; then
    cd "$curdir" || return 1
    cargo run
    return $?
  fi
  tmpdir=$(mktemp -d)
  if [ -f "$curdir/../Cargo.toml" ]; then
    # reason to copy Cargo.toml is to get the dependencies.
    # but maybe this should copy the entire directory?
    setup "$tmpdir" "$1" "$curdir/../Cargo.toml"
  else
    setup "$tmpdir" "$1"
  fi
  cd "$tmpdir" || return 1
  cargo run
  rm -rf "$tmpdir"
}

cargo_test() {
  curdir=$(dirname "$1")
  echo "$curdir"
  # export RUST_BACKTRACE=1
  if [ -f "$curdir/Cargo.toml" ]; then
    cd "$curdir" || exit 1
    shift
    cargo test "$@"
  # elif [ "$(basename "$curdir")" = "tests" ] && [ -f "$curdir/../Cargo.toml" ]; then
  elif [ -f "$curdir/../Cargo.toml" ]; then
    cd "$curdir/.." || exit 1
    shift
    cargo test "$@"
  else
    dirname=$(mktemp -d)
    setup "$dirname" "$1"
    shift
    cargo test "$@"
    rm -rf "$dirname"
  fi
}

main() {
  POSITIONAL=()
  while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
    -c | --make-cargo)
      MK_CARGO=YES
      shift
      ;;
    -t | --test)
      TEST=YES
      shift
      ;;
    *)                   # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift              # past argument
      ;;
    esac
  done
  set -- "${POSITIONAL[@]}" # restore positional parameters

  if [ "$MK_CARGO" = YES ]; then
    mk_cargo "$1"
  elif [ "$TEST" = YES ]; then
    cargo_test "${POSITIONAL[@]}"
  else
    cargo_run "${POSITIONAL[@]}"
  fi
}

echo "$@"
main "$@"
