#!/usr/bin/env bash
usage() {
  echo "usage: xf [-x executable(default nvim)] SEARCH_WORD"
  exit 0
}

positional=()
while [[ $# -gt 0 ]]
do
  key="$1"
  case $key in
    -x|--executable)
      executable="$2"
      shift
      shift
      ;;
    -h|--help)
      usage
      ;;
    *)
      positional+=("$1")
      shift
      ;;
  esac
done
if [[ -z "$executable" ]] ; then
  executable=nvim
fi

set -- "${positional[@]}" # restore positional parameters
if [[ ${#positional[@]} -eq 0 ]]; then
  search_word=""
elif [[ ${#positional[@]} -eq 1 ]]; then
  search_word=${#positional[0]}
elif [[ ${#positional[@]} -gt 1 ]]; then
  echo "more than 1 search words provided."
  usage
  exit 1
fi
fd --type f --hidden --follow --exclude .git "$search_word" \
  | fzf --preview "bat --color always --style numbers {1}" \
  | xargs $executable
