[tools]
# Runtimes
node = "lts"
go = "latest"
bun = "latest"

# Editor & Core CLI
neovim = "latest"
ripgrep = "latest"
fd = "latest"
bat = "latest"
fzf = "latest"
jq = "latest"
shellcheck = "latest"
shfmt = "latest"
zoxide = "latest"
lazygit = "latest"
lazydocker = "latest"
stylua = "latest"
"aqua:gokcehan/lf" = "latest"
herdr = "latest"
antigravity-cli = "latest"
yazi = "latest"

# Omarchy & AI tools
codex = "latest"
gemini = { version = "latest", allow_builds = ["@github/keytar", "node-pty"] }
gh = "latest"
"pipx:hermes-agent" = { version = "latest", extras = "all" }
uv = "latest"

[settings.upgrade]
auto_prune = false

